//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AZ_ACCOUNT
    {
        public string ACCOUNT_NUMBER { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string CATEGORY { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<double> PRINCIPAL { get; set; }
        public Nullable<System.DateTime> VALUE_DATE { get; set; }
        public Nullable<System.DateTime> MATURITY_DATE { get; set; }
        public string PASSBOOK_NUMBER { get; set; }
        public string AZ_NARRATIVE { get; set; }
        public Nullable<decimal> INTEREST_RATE { get; set; }
        public string TERM { get; set; }
        public string CO_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string THAM_GIA_KM { get; set; }
    }
}
