//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CITIZEN_ID { get; set; }
        public string CITIZEN_DATE { get; set; }
        public string CITI_IS_PLACE { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string FACSIMILE { get; set; }
        public string EMAIL { get; set; }
        public string WEBPAGE { get; set; }
        public string BIRTH_INCORP_DATE { get; set; }
        public string GENDER { get; set; }
        public string SECTOR { get; set; }
        public string NATIONALITY { get; set; }
        public string COMPANY { get; set; }
        public string CO_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string LEGAL_ID { get; set; }
        public string HOMEPHONE { get; set; }
    }
}
