//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuckySerial
    {
        public long id { get; set; }
        public string book_number { get; set; }
        public string customer_id { get; set; }
        public int seq { get; set; }
        public string SavedBy { get; set; }
        public Nullable<System.DateTime> input_time { get; set; }
    }
}
