//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permision
    {
        public byte ID { get; set; }
        public string Permision1 { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
