//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromotionEntities : DbContext
    {
        public PromotionEntities()
            : base("name=PromotionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BLACKLIST_CUSTOMER> BLACKLIST_CUSTOMER { get; set; }
        public DbSet<COMPANY> COMPANies { get; set; }
        public DbSet<DAO> DAOs { get; set; }
        public DbSet<DAO_COMPANY> DAO_COMPANY { get; set; }
        public DbSet<DelSerial> DelSerials { get; set; }
        public DbSet<LiXi> LiXis { get; set; }
        public DbSet<LuckySerial> LuckySerials { get; set; }
        public DbSet<Permision> Permisions { get; set; }
        public DbSet<SerialByMonth> SerialByMonths { get; set; }
        public DbSet<SerialByWeek> SerialByWeeks { get; set; }
        public DbSet<SerialMax> SerialMaxes { get; set; }
        public DbSet<SerialResult> SerialResults { get; set; }
        public DbSet<STAFF_USER> STAFF_USER { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
