//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialByWeek
    {
        public long Id { get; set; }
        public int Period { get; set; }
        public double VND { get; set; }
        public double USD { get; set; }
        public int SoPhieu { get; set; }
        public System.DateTime effect_date { get; set; }
    }
}
