//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialResult
    {
        public long id { get; set; }
        public string customer_id { get; set; }
        public string customer_name { get; set; }
        public string CMND { get; set; }
        public string tel { get; set; }
        public string book_number { get; set; }
        public Nullable<double> amount { get; set; }
        public int kyhan { get; set; }
        public string currency { get; set; }
        public string Serials { get; set; }
        public Nullable<System.DateTime> Input_time { get; set; }
        public string SavedBy { get; set; }
        public string Sector { get; set; }
        public Nullable<System.DateTime> EFFECT_DATE { get; set; }
        public Nullable<System.DateTime> MATURITY_DATE { get; set; }
        public string ACCT_NUM { get; set; }
        public string CO_CODE { get; set; }
        public string TERM { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<int> cMoney { get; set; }
        public Nullable<int> Seq { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DAO_CODE { get; set; }
        public string DEPT_CODE { get; set; }
    }
}
