//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_USER
    {
        public string USERNAME { get; set; }
        public string DAO_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string HO_TEN { get; set; }
        public string PHONG_BAN { get; set; }
        public string RANK { get; set; }
        public Nullable<bool> IS_USE { get; set; }
        public string CREATED_BY { get; set; }
        public string REP_DEPARTMENT { get; set; }
        public string T24_USERID { get; set; }
        public string ACCOUNT_OFFICER { get; set; }
    }
}
