//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPPromotion.Serial.T24DataMining {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="T24DataMining.IDataMining")]
    public interface IDataMining {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMining/Connect", ReplyAction="http://tempuri.org/IDataMining/ConnectResponse")]
        bool Connect(string strHost, string strPort, string strServiceName, string strUserID, string strPassword, ref string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMining/ExecSQL", ReplyAction="http://tempuri.org/IDataMining/ExecSQLResponse")]
        System.Data.DataSet ExecSQL(string strHost, string strPort, string strServiceName, string strUserID, string strPassword, string strSqlCommand, string StandardSelectionName, bool removeEmptyColumn, ref bool result, ref string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMining/ExecSQLWithRange", ReplyAction="http://tempuri.org/IDataMining/ExecSQLWithRangeResponse")]
        System.Data.DataSet ExecSQLWithRange(string strHost, string strPort, string strServiceName, string strUserID, string strPassword, string strSqlCommand, string StandardSelectionName, int iMinRange, int iMaxRange, bool removeEmptyColumn, ref bool result, ref string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMining/ExecOracleCommand", ReplyAction="http://tempuri.org/IDataMining/ExecOracleCommandResponse")]
        System.Data.DataSet ExecOracleCommand(string strHost, string strPort, string strServiceName, string strUserID, string strPassword, string strOracleCommand, ref bool result, ref string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMining/GetCurrentAccountByCustomerID", ReplyAction="http://tempuri.org/IDataMining/GetCurrentAccountByCustomerIDResponse")]
        System.Data.DataSet GetCurrentAccountByCustomerID(string strHost, string strPort, string strServiceName, string strSchema, string strUserID, string strPassword, string strCustomerID, bool removeEmptyColumn, ref bool result, ref string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMining/GetAllAccountByCustomerID", ReplyAction="http://tempuri.org/IDataMining/GetAllAccountByCustomerIDResponse")]
        System.Data.DataSet GetAllAccountByCustomerID(string strHost, string strPort, string strServiceName, string strSchema, string strUserID, string strPassword, string strCustomerID, bool removeEmptyColumn, ref bool result, ref string response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataMining/GetAZByCustomerID", ReplyAction="http://tempuri.org/IDataMining/GetAZByCustomerIDResponse")]
        System.Data.DataSet GetAZByCustomerID(string strHost, string strPort, string strServiceName, string strSchema, string strUserID, string strPassword, string strCustomerID, bool removeEmptyColumn, ref bool result, ref string response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataMiningChannel : GPPromotion.Serial.T24DataMining.IDataMining, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataMiningClient : System.ServiceModel.ClientBase<GPPromotion.Serial.T24DataMining.IDataMining>, GPPromotion.Serial.T24DataMining.IDataMining {
        
        public DataMiningClient() {
        }
        
        public DataMiningClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataMiningClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataMiningClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataMiningClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Connect(string strHost, string strPort, string strServiceName, string strUserID, string strPassword, ref string response) {
            return base.Channel.Connect(strHost, strPort, strServiceName, strUserID, strPassword, ref response);
        }
        
        public System.Data.DataSet ExecSQL(string strHost, string strPort, string strServiceName, string strUserID, string strPassword, string strSqlCommand, string StandardSelectionName, bool removeEmptyColumn, ref bool result, ref string response) {
            return base.Channel.ExecSQL(strHost, strPort, strServiceName, strUserID, strPassword, strSqlCommand, StandardSelectionName, removeEmptyColumn, ref result, ref response);
        }
        
        public System.Data.DataSet ExecSQLWithRange(string strHost, string strPort, string strServiceName, string strUserID, string strPassword, string strSqlCommand, string StandardSelectionName, int iMinRange, int iMaxRange, bool removeEmptyColumn, ref bool result, ref string response) {
            return base.Channel.ExecSQLWithRange(strHost, strPort, strServiceName, strUserID, strPassword, strSqlCommand, StandardSelectionName, iMinRange, iMaxRange, removeEmptyColumn, ref result, ref response);
        }
        
        public System.Data.DataSet ExecOracleCommand(string strHost, string strPort, string strServiceName, string strUserID, string strPassword, string strOracleCommand, ref bool result, ref string response) {
            return base.Channel.ExecOracleCommand(strHost, strPort, strServiceName, strUserID, strPassword, strOracleCommand, ref result, ref response);
        }
        
        public System.Data.DataSet GetCurrentAccountByCustomerID(string strHost, string strPort, string strServiceName, string strSchema, string strUserID, string strPassword, string strCustomerID, bool removeEmptyColumn, ref bool result, ref string response) {
            return base.Channel.GetCurrentAccountByCustomerID(strHost, strPort, strServiceName, strSchema, strUserID, strPassword, strCustomerID, removeEmptyColumn, ref result, ref response);
        }
        
        public System.Data.DataSet GetAllAccountByCustomerID(string strHost, string strPort, string strServiceName, string strSchema, string strUserID, string strPassword, string strCustomerID, bool removeEmptyColumn, ref bool result, ref string response) {
            return base.Channel.GetAllAccountByCustomerID(strHost, strPort, strServiceName, strSchema, strUserID, strPassword, strCustomerID, removeEmptyColumn, ref result, ref response);
        }
        
        public System.Data.DataSet GetAZByCustomerID(string strHost, string strPort, string strServiceName, string strSchema, string strUserID, string strPassword, string strCustomerID, bool removeEmptyColumn, ref bool result, ref string response) {
            return base.Channel.GetAZByCustomerID(strHost, strPort, strServiceName, strSchema, strUserID, strPassword, strCustomerID, removeEmptyColumn, ref result, ref response);
        }
    }
}
